// ═══════════════════════════════════════════════════════════════════════════
// NumerOwls — Competition Question Bank v2
// 160 original questions inspired by:
//   • Primary Maths Challenge (PMC) — UK primary competition
//   • UKMT Junior Maths Challenge — adapted down for Years 5-6
//   • Math Kangaroo Pre-Écolier (Y1-2) and Écolier (Y3-4)
//   • AMC 8 — adapted for primary age groups
//
// ALL questions are original. No text is reproduced from any source.
// Competition names are cited only to indicate style inspiration.
// ═══════════════════════════════════════════════════════════════════════════

import type { Question } from "./questionBank";

// ─────────────────────────────────────────────────────────────────────────────
// ADDITION & SUBTRACTION
// ─────────────────────────────────────────────────────────────────────────────
export const compAdditionQuestions: Question[] = [
  {
    id: "ca_y2_01", skill: "addition", year: 2, difficulty: 1, type: "mcq",
    text: "I think of a number, add 7 and get 15. What was my number?",
    options: ["6", "7", "8", "9", "10"],
    answer: "8",
    explanation: "Work backwards: 15 − 7 = 8.",
    style: "think-of-a-number", source: "original", points: 3,
  },
  {
    id: "ca_y3_01", skill: "addition", year: 3, difficulty: 2, type: "mcq",
    text: "I think of a number, double it, then subtract 9. I get 13. What was my number?",
    options: ["9", "10", "11", "12", "13"],
    answer: "11",
    explanation: "Work backwards: 13 + 9 = 22, then 22 ÷ 2 = 11.",
    style: "think-of-a-number", source: "original", points: 3,
  },
  {
    id: "ca_y4_01", skill: "addition", year: 4, difficulty: 2, type: "mcq",
    text: "I think of a number, multiply by 3, then add 8. I get 35. What was my number?",
    options: ["7", "8", "9", "10", "11"],
    answer: "9",
    explanation: "Work backwards: 35 − 8 = 27, then 27 ÷ 3 = 9.",
    style: "think-of-a-number", source: "original", points: 4,
  },
  {
    id: "ca_y3_02", skill: "addition", year: 3, difficulty: 2, type: "mcq",
    text: "Three consecutive numbers add up to 39. What is the smallest?",
    options: ["11", "12", "13", "14", "15"],
    answer: "12",
    explanation: "The middle number = 39 ÷ 3 = 13, so the three numbers are 12, 13, 14. Smallest = 12.",
    style: "consecutive-numbers", source: "original", points: 4,
  },
  {
    id: "ca_y5_01", skill: "addition", year: 5, difficulty: 2, type: "mcq",
    text: "Five consecutive even numbers add up to 70. What is the largest?",
    options: ["12", "14", "16", "18", "20"],
    answer: "18",
    explanation: "Middle number = 70 ÷ 5 = 14. The five numbers are 10, 12, 14, 16, 18. Largest = 18.",
    style: "consecutive-numbers", source: "original", points: 4,
  },
  {
    id: "ca_y2_02", skill: "addition", year: 2, difficulty: 1, type: "mcq",
    text: "3□ + □4 = 71. Both missing digits are the same number. What is the missing digit?",
    options: ["2", "3", "4", "5", "6"],
    answer: "3",
    explanation: "37 + 34 = 71. Both missing digits are 3.",
    style: "digit-puzzle", source: "original", points: 3,
  },
  {
    id: "ca_y4_03", skill: "addition", year: 4, difficulty: 2, type: "mcq",
    text: "How many 2-digit palindromes are there? (A palindrome reads the same forwards and backwards, e.g. 33.)",
    options: ["7", "8", "9", "10", "11"],
    answer: "9",
    explanation: "2-digit palindromes have the same tens and units digit: 11, 22, 33, 44, 55, 66, 77, 88, 99. That is 9.",
    style: "palindrome-counting", source: "original", points: 3,
  },
  {
    id: "ca_y5_02", skill: "addition", year: 5, difficulty: 3, type: "mcq",
    text: "How many 3-digit palindromes are there?",
    options: ["81", "90", "99", "100", "110"],
    answer: "90",
    explanation: "A 3-digit palindrome has form ABA. A can be 1–9 (9 choices), B can be 0–9 (10 choices). Total = 9 × 10 = 90.",
    style: "palindrome-counting", source: "original", points: 5,
  },
  {
    id: "ca_y3_03", skill: "addition", year: 3, difficulty: 1, type: "mcq",
    text: "A baker makes 48 rolls in the morning and 36 in the afternoon. She sells 57. How many rolls are left?",
    options: ["21", "25", "27", "29", "31"],
    answer: "27",
    explanation: "Total = 48 + 36 = 84. Remaining = 84 − 57 = 27.",
    style: "standard", source: "pmc", points: 3,
  },
  {
    id: "ca_y4_04", skill: "addition", year: 4, difficulty: 1, type: "mcq",
    text: "At midnight the temperature is −8°C. By noon it has risen by 15°C. What is the temperature at noon?",
    options: ["5°C", "6°C", "7°C", "8°C", "23°C"],
    answer: "7°C",
    explanation: "−8 + 15 = 7°C.",
    style: "standard", source: "pmc", points: 3,
  },
  {
    id: "ca_y5_04", skill: "addition", year: 5, difficulty: 2, type: "mcq",
    text: "City A is 14°C. City B is 23°C warmer than City A. City C is 9°C colder than City B. What is the temperature in City C?",
    options: ["18°C", "24°C", "26°C", "28°C", "30°C"],
    answer: "28°C",
    explanation: "City B = 14 + 23 = 37°C. City C = 37 − 9 = 28°C.",
    style: "standard", source: "original", points: 3,
  },
  {
    id: "ca_y5_05", skill: "addition", year: 5, difficulty: 3, type: "mcq",
    text: "The sum of two numbers is 100. Their difference is 24. What is the larger number?",
    options: ["56", "58", "60", "62", "64"],
    answer: "62",
    explanation: "Larger = (100 + 24) ÷ 2 = 62. Smaller = (100 − 24) ÷ 2 = 38.",
    style: "simultaneous-constraints", source: "ukmt", points: 4,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// MULTIPLICATION & DIVISION
// ─────────────────────────────────────────────────────────────────────────────
export const compMultiplicationQuestions: Question[] = [
  {
    id: "cm_y4_01", skill: "multiplication", year: 4, difficulty: 1, type: "mcq",
    text: "A number is divisible by 3 if the sum of its digits is divisible by 3. Which of these is divisible by 3?",
    options: ["112", "124", "135", "148", "157"],
    answer: "135",
    explanation: "1 + 3 + 5 = 9, which is divisible by 3. So 135 is divisible by 3.",
    style: "arithmetic-comparison", source: "ukmt", points: 3,
  },
  {
    id: "cm_y5_01", skill: "multiplication", year: 5, difficulty: 2, type: "mcq",
    text: "Which of these numbers is divisible by both 4 and 6?",
    options: ["20", "24", "28", "32", "38"],
    answer: "24",
    explanation: "LCM(4, 6) = 12. From the options, 24 = 12 × 2. ✓",
    style: "arithmetic-comparison", source: "original", points: 3,
  },
  {
    id: "cm_y6_01", skill: "multiplication", year: 6, difficulty: 3, type: "mcq",
    text: "A 3-digit number □7□ is divisible by 9. Both missing digits are the same. What is that digit?",
    options: ["1", "2", "3", "4", "5"],
    answer: "1",
    explanation: "Sum of digits = □ + 7 + □ = 2□ + 7. For divisibility by 9: 2□ + 7 = 9 → □ = 1. Number = 171.",
    style: "digit-puzzle", source: "ukmt", points: 5,
  },
  {
    id: "cm_y3_01", skill: "multiplication", year: 3, difficulty: 1, type: "mcq",
    text: "A machine doubles a number then adds 1. What is the output when the input is 7?",
    options: ["13", "14", "15", "16", "17"],
    answer: "15",
    explanation: "7 × 2 = 14, then 14 + 1 = 15.",
    style: "function-machine", source: "original", points: 3,
  },
  {
    id: "cm_y4_02", skill: "multiplication", year: 4, difficulty: 2, type: "mcq",
    text: "A machine multiplies a number by 3 then subtracts 5. The output is 22. What was the input?",
    options: ["7", "8", "9", "10", "11"],
    answer: "9",
    explanation: "Work backwards: 22 + 5 = 27, then 27 ÷ 3 = 9.",
    style: "function-machine", source: "original", points: 3,
  },
  {
    id: "cm_y5_02", skill: "multiplication", year: 5, difficulty: 2, type: "mcq",
    text: "Machine A multiplies by 4. Machine B adds 7. They are chained (A first, then B). An input of □ gives a final output of 55. What is □?",
    options: ["10", "11", "12", "13", "14"],
    answer: "12",
    explanation: "Work backwards: 55 − 7 = 48, then 48 ÷ 4 = 12.",
    style: "function-machine", source: "kangaroo", points: 4,
  },
  {
    id: "cm_y4_03", skill: "multiplication", year: 4, difficulty: 2, type: "mcq",
    text: "How many factors does 36 have?",
    options: ["7", "8", "9", "10", "11"],
    answer: "9",
    explanation: "Factors of 36: 1, 2, 3, 4, 6, 9, 12, 18, 36. That is 9 factors.",
    style: "arithmetic-comparison", source: "ukmt", points: 4,
  },
  {
    id: "cm_y5_03", skill: "multiplication", year: 5, difficulty: 2, type: "mcq",
    text: "What is the smallest number with exactly 3 factors?",
    options: ["2", "3", "4", "6", "9"],
    answer: "4",
    explanation: "A number with exactly 3 factors must be a square of a prime. 4 = 2² has factors 1, 2, 4.",
    style: "arithmetic-comparison", source: "ukmt", points: 4,
  },
  {
    id: "cm_y6_02", skill: "multiplication", year: 6, difficulty: 3, type: "mcq",
    text: "The product of three consecutive odd numbers is 105. What is the largest?",
    options: ["5", "7", "9", "11", "13"],
    answer: "7",
    explanation: "3 × 5 × 7 = 105. The three consecutive odd numbers are 3, 5, 7. Largest is 7.",
    style: "consecutive-numbers", source: "original", points: 5,
  },
  {
    id: "cm_y3_02", skill: "multiplication", year: 3, difficulty: 1, type: "mcq",
    text: "Sam is 3 times as old as his sister. Their ages add up to 20. How old is Sam?",
    options: ["12", "13", "14", "15", "16"],
    answer: "15",
    explanation: "Sister = 20 ÷ 4 = 5. Sam = 3 × 5 = 15.",
    style: "age-problems", source: "pmc", points: 3,
  },
  {
    id: "cm_y5_04", skill: "multiplication", year: 5, difficulty: 3, type: "mcq",
    text: "In 5 years Mia will be twice as old as she was 4 years ago. How old is Mia now?",
    options: ["11", "12", "13", "14", "15"],
    answer: "13",
    explanation: "Let Mia's age = x. x + 5 = 2(x − 4) → x + 5 = 2x − 8 → x = 13.",
    style: "age-problems", source: "ukmt", points: 5,
  },
  {
    id: "cm_y4_04", skill: "multiplication", year: 4, difficulty: 1, type: "mcq",
    text: "Juice costs £1.20 for 400ml or £2.10 for 750ml. Which is better value?",
    options: ["400ml bottle", "750ml bottle", "Both the same", "Can't tell", "Depends on size"],
    answer: "750ml bottle",
    explanation: "400ml: 120p ÷ 400 = 0.30p/ml. 750ml: 210p ÷ 750 = 0.28p/ml. The 750ml is cheaper per ml.",
    style: "best-value", source: "pmc", points: 3,
  },
  {
    id: "cm_y5_05", skill: "multiplication", year: 5, difficulty: 2, type: "mcq",
    text: "A shop sells 3 pens for £2.40 or 5 pens for £3.75. Which is cheaper per pen?",
    options: ["3 for £2.40", "5 for £3.75", "Same price", "Neither option", "Can't tell"],
    answer: "5 for £3.75",
    explanation: "3 for £2.40 = 80p each. 5 for £3.75 = 75p each. The pack of 5 is cheaper per pen.",
    style: "best-value", source: "original", points: 4,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// FRACTIONS & DECIMALS
// ─────────────────────────────────────────────────────────────────────────────
export const compFractionQuestions: Question[] = [
  {
    id: "cf_y3_01", skill: "fractions", year: 3, difficulty: 1, type: "mcq",
    text: "What fraction of 60 is 15?",
    options: ["1/6", "1/5", "1/4", "1/3", "1/2"],
    answer: "1/4",
    explanation: "15/60 = 1/4.",
    style: "standard", source: "original", points: 3,
  },
  {
    id: "cf_y4_01", skill: "fractions", year: 4, difficulty: 2, type: "mcq",
    text: "A bag has red and blue sweets. 3/8 are red. There are 24 sweets altogether. How many are blue?",
    options: ["8", "9", "12", "15", "16"],
    answer: "15",
    explanation: "Red = 3/8 × 24 = 9. Blue = 24 − 9 = 15.",
    style: "fraction-remaining", source: "pmc", points: 3,
  },
  {
    id: "cf_y5_01", skill: "fractions", year: 5, difficulty: 2, type: "mcq",
    text: "I spend 2/5 of my pocket money on Monday and 1/3 on Tuesday. What fraction is left?",
    options: ["4/15", "3/15", "3/8", "1/4", "7/15"],
    answer: "4/15",
    explanation: "Spent = 2/5 + 1/3 = 6/15 + 5/15 = 11/15. Left = 4/15.",
    style: "fraction-remaining", source: "pmc", points: 4,
  },
  {
    id: "cf_y6_01", skill: "fractions", year: 6, difficulty: 3, type: "mcq",
    text: "A tank is 3/4 full. After 30 litres are removed it is 1/2 full. How many litres does the full tank hold?",
    options: ["80L", "100L", "120L", "140L", "150L"],
    answer: "120L",
    explanation: "3/4 − 1/2 = 1/4 of the tank = 30 litres. Full tank = 30 × 4 = 120 litres.",
    style: "fraction-remaining", source: "ukmt", points: 5,
  },
  {
    id: "cf_y3_02", skill: "fractions", year: 3, difficulty: 1, type: "mcq",
    text: "A rectangle is cut into 8 equal parts. 3 parts are shaded. What fraction is NOT shaded?",
    options: ["3/8", "4/8", "5/8", "6/8", "7/8"],
    answer: "5/8",
    explanation: "Not shaded = 8/8 − 3/8 = 5/8.",
    style: "fraction-of-shape", source: "original", points: 3,
  },
  {
    id: "cf_y5_02", skill: "fractions", year: 5, difficulty: 2, type: "mcq",
    text: "What is 35% of 140?",
    options: ["42", "46", "49", "52", "56"],
    answer: "49",
    explanation: "10% of 140 = 14. 35% = 14 × 3.5 = 49.",
    style: "standard", source: "pmc", points: 3,
  },
  {
    id: "cf_y5_03", skill: "fractions", year: 5, difficulty: 2, type: "mcq",
    text: "A jacket costs £60 and is reduced by 15%. What is the sale price?",
    options: ["£48", "£50", "£51", "£54", "£56"],
    answer: "£51",
    explanation: "15% of £60 = £9. Sale price = £60 − £9 = £51.",
    style: "percentage-change", source: "pmc", points: 3,
  },
  {
    id: "cf_y6_02", skill: "fractions", year: 6, difficulty: 3, type: "mcq",
    text: "A price increases by 20% then decreases by 20%. The original price was £50. What is the final price?",
    options: ["£46", "£48", "£50", "£52", "£54"],
    answer: "£48",
    explanation: "After 20% increase: £50 × 1.2 = £60. After 20% decrease: £60 × 0.8 = £48.",
    style: "percentage-change", source: "ukmt", points: 5,
  },
  {
    id: "cf_y5_04", skill: "fractions", year: 5, difficulty: 2, type: "mcq",
    text: "Paint is mixed red to white in the ratio 2:3. I need 20 litres altogether. How much red paint do I need?",
    options: ["6L", "7L", "8L", "9L", "10L"],
    answer: "8L",
    explanation: "Total parts = 5. Red = 2/5 × 20 = 8 litres.",
    style: "ratio-word-problem", source: "pmc", points: 3,
  },
  {
    id: "cf_y6_03", skill: "fractions", year: 6, difficulty: 3, type: "mcq",
    text: "The ratio of boys to girls in a class is 3:4. There are 28 pupils altogether. How many more girls than boys are there?",
    options: ["2", "3", "4", "5", "6"],
    answer: "4",
    explanation: "Each part = 28 ÷ 7 = 4. Boys = 12, Girls = 16. Difference = 4.",
    style: "ratio-word-problem", source: "ukmt", points: 4,
  },
  {
    id: "cf_y6_04", skill: "fractions", year: 6, difficulty: 3, type: "mcq",
    text: "0.3 × 0.4 = ?",
    options: ["0.007", "0.07", "0.12", "1.2", "12"],
    answer: "0.12",
    explanation: "3 × 4 = 12. Two decimal places in total (0.3 has 1, 0.4 has 1). So answer = 0.12.",
    style: "standard", source: "original", points: 3,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SHAPES & GEOMETRY
// ─────────────────────────────────────────────────────────────────────────────
export const compShapesQuestions: Question[] = [
  {
    id: "cs_y2_01", skill: "shapes", year: 2, difficulty: 1, type: "mcq",
    text: "Both diagonals of a rectangle are drawn. How many triangles are there altogether?",
    options: ["2", "3", "4", "6", "8"],
    answer: "4",
    explanation: "Drawing both diagonals of a rectangle creates exactly 4 triangles.",
    style: "counting-shapes", source: "kangaroo", points: 3,
  },
  {
    id: "cs_y3_01", skill: "shapes", year: 3, difficulty: 2, type: "mcq",
    text: "A large equilateral triangle is divided into 4 smaller equal triangles. How many triangles are there in total?",
    options: ["4", "5", "6", "7", "8"],
    answer: "5",
    explanation: "4 small triangles + 1 large triangle = 5 triangles in total.",
    style: "counting-shapes", source: "kangaroo", points: 3,
  },
  {
    id: "cs_y4_01", skill: "shapes", year: 4, difficulty: 2, type: "mcq",
    text: "How many squares of any size are in a 3×3 grid of unit squares?",
    options: ["9", "12", "13", "14", "16"],
    answer: "14",
    explanation: "1×1 squares: 9. 2×2 squares: 4. 3×3 squares: 1. Total = 14.",
    style: "counting-shapes", source: "amc8", points: 4,
  },
  {
    id: "cs_y3_02", skill: "shapes", year: 3, difficulty: 1, type: "mcq",
    text: "A rectangle has perimeter 24cm and length 8cm. What is its width?",
    options: ["3cm", "4cm", "5cm", "6cm", "8cm"],
    answer: "4cm",
    explanation: "24 = 2(8 + w) → 12 = 8 + w → w = 4cm.",
    style: "compound-perimeter", source: "original", points: 3,
  },
  {
    id: "cs_y4_02", skill: "shapes", year: 4, difficulty: 2, type: "mcq",
    text: "An L-shape is made by removing a 2×2 square from the corner of a 5×4 rectangle. What is the area of the L-shape?",
    options: ["12cm²", "14cm²", "16cm²", "18cm²", "20cm²"],
    answer: "16cm²",
    explanation: "5 × 4 = 20cm². Remove 2 × 2 = 4cm². L-shape = 16cm².",
    style: "floor-plan-area", source: "pmc", points: 3,
  },
  {
    id: "cs_y4_03", skill: "shapes", year: 4, difficulty: 1, type: "mcq",
    text: "A square has side 6cm. A border 1cm wide is drawn inside the square. What is the area of the border strip?",
    options: ["16cm²", "18cm²", "20cm²", "22cm²", "24cm²"],
    answer: "20cm²",
    explanation: "Outer square = 36cm². Inner square = 4×4 = 16cm². Border = 36 − 16 = 20cm².",
    style: "area-border-frame", source: "kangaroo", points: 4,
  },
  {
    id: "cs_y4_04", skill: "shapes", year: 4, difficulty: 2, type: "mcq",
    text: "A cube has surface area 96cm². What is the length of one edge?",
    options: ["3cm", "4cm", "5cm", "6cm", "7cm"],
    answer: "4cm",
    explanation: "6 faces. Each face = 96 ÷ 6 = 16cm². Side = √16 = 4cm.",
    style: "net-3d-shape", source: "original", points: 4,
  },
  {
    id: "cs_y5_03", skill: "shapes", year: 5, difficulty: 2, type: "mcq",
    text: "A cube has edge length 3cm. How many 1×1×1 unit cubes fit inside?",
    options: ["9", "18", "24", "27", "36"],
    answer: "27",
    explanation: "Volume = 3 × 3 × 3 = 27.",
    style: "3d-counting", source: "original", points: 3,
  },
  {
    id: "cs_y3_03", skill: "shapes", year: 3, difficulty: 1, type: "mcq",
    text: "Harry faces North. He turns 90° clockwise, then 180° clockwise. Which direction does he now face?",
    options: ["North", "East", "South", "West", "North-East"],
    answer: "West",
    explanation: "North → 90° clockwise → East → 180° clockwise → West.",
    style: "direction-rotation", source: "pmc", points: 3,
  },
  {
    id: "cs_y4_05", skill: "shapes", year: 4, difficulty: 2, type: "mcq",
    text: "A robot starts facing East. It makes 5 quarter-turns clockwise. Which direction does it face now?",
    options: ["North", "East", "South", "West", "Up"],
    answer: "South",
    explanation: "4 quarter-turns = full rotation. 5th quarter-turn from East → South.",
    style: "direction-rotation", source: "kangaroo", points: 3,
  },
  {
    id: "cs_y5_04", skill: "shapes", year: 5, difficulty: 2, type: "mcq",
    text: "What is the interior angle of a regular hexagon?",
    options: ["100°", "108°", "110°", "120°", "135°"],
    answer: "120°",
    explanation: "Sum of interior angles = (6−2) × 180° = 720°. Each angle = 720° ÷ 6 = 120°.",
    style: "angle-polygon", source: "ukmt", points: 4,
  },
  {
    id: "cs_y6_02", skill: "shapes", year: 6, difficulty: 3, type: "mcq",
    text: "A regular pentagon has interior angles that all add up to 540°. What is each interior angle?",
    options: ["96°", "100°", "104°", "108°", "112°"],
    answer: "108°",
    explanation: "540° ÷ 5 = 108°.",
    style: "angle-polygon", source: "ukmt", points: 4,
  },
  {
    id: "cs_y5_05", skill: "shapes", year: 5, difficulty: 3, type: "mcq",
    text: "A right-angled triangle has legs of 6cm and 8cm. What is the length of the hypotenuse?",
    options: ["9cm", "10cm", "11cm", "12cm", "14cm"],
    answer: "10cm",
    explanation: "6² + 8² = 36 + 64 = 100. √100 = 10cm.",
    style: "standard", source: "original", points: 4,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// PATTERNS & SEQUENCES
// ─────────────────────────────────────────────────────────────────────────────
export const compPatternsQuestions: Question[] = [
  {
    id: "cp_y3_01", skill: "patterns", year: 3, difficulty: 1, type: "mcq",
    text: "The triangular numbers go: 1, 3, 6, 10, 15, … What is the next one?",
    options: ["18", "19", "20", "21", "22"],
    answer: "21",
    explanation: "Add increasing integers: +2, +3, +4, +5, +6. Next = 15 + 6 = 21.",
    style: "triangular-numbers", source: "original", points: 3,
  },
  {
    id: "cp_y5_01", skill: "patterns", year: 5, difficulty: 3, type: "mcq",
    text: "What is the 10th triangular number?",
    options: ["45", "50", "55", "60", "65"],
    answer: "55",
    explanation: "nth triangular number = n(n+1)/2. For n=10: 10 × 11 / 2 = 55.",
    style: "triangular-numbers", source: "original", points: 5,
  },
  {
    id: "cp_y4_01", skill: "patterns", year: 4, difficulty: 2, type: "mcq",
    text: "Which square number is between 50 and 70?",
    options: ["49", "56", "64", "72", "81"],
    answer: "64",
    explanation: "8² = 64, which lies between 50 and 70.",
    style: "arithmetic-comparison", source: "original", points: 3,
  },
  {
    id: "cp_y3_02", skill: "patterns", year: 3, difficulty: 1, type: "mcq",
    text: "What is the next number in the sequence: 2, 5, 11, 23, 47, …?",
    options: ["71", "83", "88", "93", "95"],
    answer: "95",
    explanation: "Rule: multiply by 2 then add 1. 47 × 2 + 1 = 95.",
    style: "alternating-sequence", source: "original", points: 3,
  },
  {
    id: "cp_y4_02", skill: "patterns", year: 4, difficulty: 2, type: "mcq",
    text: "The sequence: 1, 2, 4, 8, 16, … What is the 8th term?",
    options: ["64", "96", "128", "256", "512"],
    answer: "128",
    explanation: "Each term doubles. 8th term = 2⁷ = 128.",
    style: "arithmetic-sequence", source: "original", points: 4,
  },
  {
    id: "cp_y4_03", skill: "patterns", year: 4, difficulty: 2, type: "mcq",
    text: "What is the sum of all odd numbers from 1 to 19?",
    options: ["81", "90", "100", "110", "121"],
    answer: "100",
    explanation: "Sum of first n odd numbers = n². There are 10 odd numbers from 1 to 19. Sum = 10² = 100.",
    style: "arithmetic-sequence", source: "ukmt", points: 4,
  },
  {
    id: "cp_y5_03", skill: "patterns", year: 5, difficulty: 3, type: "mcq",
    text: "What is 1 + 2 + 3 + … + 20?",
    options: ["180", "190", "200", "210", "220"],
    answer: "210",
    explanation: "Sum = n(n+1)/2 = 20 × 21 / 2 = 210.",
    style: "arithmetic-sequence", source: "original", points: 4,
  },
  {
    id: "cp_y4_04", skill: "patterns", year: 4, difficulty: 1, type: "mcq",
    text: "Today is Monday. What day of the week will it be in 20 days?",
    options: ["Monday", "Tuesday", "Wednesday", "Sunday", "Friday"],
    answer: "Sunday",
    explanation: "20 ÷ 7 = 2 remainder 6. Count 6 days from Monday: Tue, Wed, Thu, Fri, Sat, Sun.",
    style: "calendar-arithmetic", source: "pmc", points: 3,
  },
  {
    id: "cp_y5_04", skill: "patterns", year: 5, difficulty: 2, type: "mcq",
    text: "January 1st is a Wednesday. What day is February 1st (not a leap year)?",
    options: ["Friday", "Saturday", "Sunday", "Monday", "Tuesday"],
    answer: "Saturday",
    explanation: "January has 31 days. 31 = 4×7 + 3. So Feb 1 is 3 days after Wednesday = Saturday.",
    style: "calendar-arithmetic", source: "kangaroo", points: 4,
  },
  {
    id: "cp_y6_01", skill: "patterns", year: 6, difficulty: 3, type: "mcq",
    text: "My birthday is on a Saturday in 2025. On what day is it in 2026 (not a leap year)?",
    options: ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday"],
    answer: "Sunday",
    explanation: "365 = 52 × 7 + 1. The day advances by 1. Saturday → Sunday.",
    style: "calendar-arithmetic", source: "original", points: 4,
  },
  {
    id: "cp_y4_05", skill: "patterns", year: 4, difficulty: 2, type: "mcq",
    text: "The digits of a 2-digit number add up to 11. The tens digit is 3 more than the units digit. What is the number?",
    options: ["47", "56", "65", "74", "83"],
    answer: "74",
    explanation: "Let units = u. Tens = u+3. u + u+3 = 11 → u = 4. Number = 74.",
    style: "digit-puzzle", source: "ukmt", points: 4,
  },
  {
    id: "cp_y5_05", skill: "patterns", year: 5, difficulty: 3, type: "mcq",
    text: "A 3-digit number whose digits are three consecutive numbers in increasing order is divisible by 7. What is the number?",
    options: ["123", "234", "345", "456", "567"],
    answer: "567",
    explanation: "Check: 123÷7 ≈ 17.6 ✗, 234÷7 ≈ 33.4 ✗, 345÷7 ≈ 49.3 ✗, 456÷7 ≈ 65.1 ✗, 567÷7 = 81 ✓.",
    style: "digit-puzzle", source: "original", points: 5,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// LOGIC & WORD PROBLEMS
// ─────────────────────────────────────────────────────────────────────────────
export const compLogicQuestions: Question[] = [
  {
    id: "cl_y4_01", skill: "logic", year: 4, difficulty: 2, type: "mcq",
    text: "Alex always tells the truth. Bea always lies. Alex says 'I am older than Bea'. Bea also says 'Alex is older than me'. Which is actually true?",
    options: [
      "Alex is older than Bea",
      "Bea is older than Alex",
      "They are the same age",
      "Can't be determined",
      "Neither statement is valid",
    ],
    answer: "Alex is older than Bea",
    explanation: "Alex (truth-teller) says Alex > Bea — this is true. Bea (liar) says 'Alex is older than me' — a liar saying a true thing is impossible, so this scenario means Alex is indeed older (Alex's statement is the reliable one).",
    style: "liar-truth-teller", source: "ukmt", points: 4,
  },
  {
    id: "cl_y5_01", skill: "logic", year: 5, difficulty: 3, type: "mcq",
    text: "On an island, knights always tell the truth and knaves always lie. A person says: 'I am a knave.' Is this possible?",
    options: [
      "Yes — they must be a knave",
      "No — neither a knight nor a knave can say this",
      "Yes — they must be a knight",
      "Only if they are confused",
      "Yes, on odd-numbered days",
    ],
    answer: "No — neither a knight nor a knave can say this",
    explanation: "A knight can't say it (would be lying). A knave saying it would be telling the truth — also impossible. Nobody can make this statement.",
    style: "liar-truth-teller", source: "kangaroo", points: 5,
  },
  {
    id: "cl_y3_02", skill: "logic", year: 3, difficulty: 1, type: "mcq",
    text: "Four friends stand in a line. Zara is not last. Maya is directly behind Zara. Leo is first. Finn is somewhere behind Leo. In what position is Zara?",
    options: ["1st", "2nd", "3rd", "4th", "Can't tell"],
    answer: "2nd",
    explanation: "Leo is 1st. Zara is not 4th and Maya is directly behind Zara. So Zara = 2nd, Maya = 3rd, Finn = 4th.",
    style: "ordering-by-clues", source: "pmc", points: 3,
  },
  {
    id: "cl_y4_02", skill: "logic", year: 4, difficulty: 2, type: "mcq",
    text: "In a race: Priya finished before Omar. Suki finished after Nadia. Omar finished before Nadia. Who finished last?",
    options: ["Priya", "Omar", "Suki", "Nadia", "Can't tell"],
    answer: "Suki",
    explanation: "Order: Priya → Omar → Nadia → Suki. Suki is last.",
    style: "ordering-by-clues", source: "kangaroo", points: 3,
  },
  {
    id: "cl_y4_03", skill: "logic", year: 4, difficulty: 2, type: "mcq",
    text: "There are 5 different coloured socks in a drawer. You cannot see inside. What is the minimum number you must take out to guarantee a matching pair?",
    options: ["2", "3", "4", "5", "6"],
    answer: "6",
    explanation: "Worst case: the first 5 socks are all different colours. The 6th must match one.",
    style: "pigeonhole", source: "ukmt", points: 4,
  },
  {
    id: "cl_y5_02", skill: "logic", year: 5, difficulty: 3, type: "mcq",
    text: "A class of 25 pupils each chose one of 4 house colours. What is the minimum number guaranteed to share the same house colour?",
    options: ["5", "6", "7", "8", "9"],
    answer: "7",
    explanation: "⌈25 ÷ 4⌉ = ⌈6.25⌉ = 7. By the pigeonhole principle, at least 7 must share one colour.",
    style: "pigeonhole", source: "ukmt", points: 5,
  },
  {
    id: "cl_y3_03", skill: "logic", year: 3, difficulty: 1, type: "mcq",
    text: "3 apples weigh the same as 2 oranges. 1 orange weighs 90g. How much does 1 apple weigh?",
    options: ["55g", "60g", "65g", "70g", "75g"],
    answer: "60g",
    explanation: "2 oranges = 180g = 3 apples. 1 apple = 60g.",
    style: "weighing-balance", source: "kangaroo", points: 3,
  },
  {
    id: "cl_y4_04", skill: "logic", year: 4, difficulty: 2, type: "mcq",
    text: "2 cats and 1 dog weigh 19kg. 1 cat and 2 dogs weigh 17kg. How much does 1 dog weigh?",
    options: ["4kg", "5kg", "6kg", "7kg", "8kg"],
    answer: "5kg",
    explanation: "2c+d=19 and c+2d=17. Subtract: c−d=2. Substitute: 2(d+2)+d=19 → d=5.",
    style: "simultaneous-equations", source: "ukmt", points: 4,
  },
  {
    id: "cl_y4_05", skill: "logic", year: 4, difficulty: 2, type: "mcq",
    text: "In a round-robin tournament, every team plays every other team exactly once. There are 5 teams. How many games are played?",
    options: ["8", "9", "10", "11", "12"],
    answer: "10",
    explanation: "5 × 4 ÷ 2 = 10. (Every pair of teams plays once.)",
    style: "tournament-table", source: "amc8", points: 4,
  },
  {
    id: "cl_y5_04", skill: "logic", year: 5, difficulty: 3, type: "mcq",
    text: "In a knock-out tournament with 32 teams, a team is out when it loses once. How many matches are needed to find the winner?",
    options: ["16", "24", "31", "32", "63"],
    answer: "31",
    explanation: "Each match eliminates exactly 1 team. To eliminate 31 teams, you need 31 matches.",
    style: "tournament-table", source: "ukmt", points: 5,
  },
  {
    id: "cl_y5_05", skill: "logic", year: 5, difficulty: 3, type: "mcq",
    text: "Two trains are 180km apart and travel towards each other. One travels at 60km/h, the other at 30km/h. How long until they meet?",
    options: ["1h", "1.5h", "2h", "2.5h", "3h"],
    answer: "2h",
    explanation: "Combined speed = 90km/h. Time = 180 ÷ 90 = 2 hours.",
    style: "meeting-point", source: "ukmt", points: 5,
  },
  {
    id: "cl_y4_06", skill: "logic", year: 4, difficulty: 1, type: "mcq",
    text: "A snail crawls 3m every hour. How far does it travel in 4 hours and 30 minutes?",
    options: ["12m", "12.5m", "13m", "13.5m", "14m"],
    answer: "13.5m",
    explanation: "4.5 hours × 3m/h = 13.5m.",
    style: "speed-distance-time", source: "pmc", points: 3,
  },
  {
    id: "cl_y3_04", skill: "logic", year: 3, difficulty: 1, type: "mcq",
    text: "I have exactly 3 coins totalling 16p. What are the coins? (UK denominations: 1p, 2p, 5p, 10p, 20p, 50p)",
    options: [
      "10p, 5p, 1p",
      "10p, 4p, 2p",
      "5p, 5p, 6p",
      "10p, 3p, 3p",
      "10p, 2p, 4p",
    ],
    answer: "10p, 5p, 1p",
    explanation: "10 + 5 + 1 = 16p using valid UK coin denominations. ✓",
    style: "coin-combinations", source: "pmc", points: 3,
  },
  {
    id: "cl_y4_07", skill: "logic", year: 4, difficulty: 2, type: "mcq",
    text: "Using only 2p and 5p coins, what is the smallest amount less than 20p that you CANNOT make exactly?",
    options: ["1p", "3p", "7p", "9p", "11p"],
    answer: "1p",
    explanation: "You can make 2, 4, 5, 6, 7, 8, 9, 10... but you cannot make 1p or 3p. The smallest is 1p.",
    style: "coin-denomination", source: "ukmt", points: 4,
  },
  {
    id: "cl_y6_01", skill: "logic", year: 6, difficulty: 3, type: "mcq",
    text: "Three friends share a prize. Asha gets twice as much as Ben. Ben gets £10 more than Cara. Together they get £130. How much does Asha get?",
    options: ["£60", "£65", "£70", "£75", "£80"],
    answer: "£70",
    explanation: "Let Cara = c. Ben = c+10. Asha = 2(c+10). Sum: c + c+10 + 2c+20 = 130 → 4c+30=130 → c=25. Asha = 2×35 = £70.",
    style: "standard", source: "pmc", points: 5,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// SHAPE VALUE PUZZLES
// ─────────────────────────────────────────────────────────────────────────────
export const compPuzzleQuestions: Question[] = [
  {
    id: "cpz_y2_01", skill: "puzzles", year: 2, difficulty: 1, type: "mcq",
    text: "⭐ + ⭐ = 10. ⭐ + 🔵 = 9. What is 🔵?",
    options: ["3", "4", "5", "6", "7"],
    answer: "4",
    explanation: "⭐ = 5 (since 5+5=10). 5 + 🔵 = 9 → 🔵 = 4.",
    style: "simultaneous-equations", source: "original", points: 3,
  },
  {
    id: "cpz_y3_01", skill: "puzzles", year: 3, difficulty: 1, type: "mcq",
    text: "🍎 + 🍎 + 🍊 = 19. 🍎 + 🍊 = 13. What is 🍎?",
    options: ["5", "6", "7", "8", "9"],
    answer: "6",
    explanation: "Subtract the equations: 🍎 = 19 − 13 = 6.",
    style: "simultaneous-equations", source: "kangaroo", points: 3,
  },
  {
    id: "cpz_y4_01", skill: "puzzles", year: 4, difficulty: 2, type: "mcq",
    text: "🐱 × 🐱 = 🐶 + 🐶. 🐶 = 8. What is 🐱?",
    options: ["2", "3", "4", "5", "6"],
    answer: "4",
    explanation: "🐶 = 8. 🐱² = 16. 🐱 = 4.",
    style: "simultaneous-equations", source: "original", points: 4,
  },
  {
    id: "cpz_y4_02", skill: "puzzles", year: 4, difficulty: 2, type: "mcq",
    text: "In a 3×3 magic square where all rows, columns and diagonals sum to the same number, the centre is 5. What is the magic total?",
    options: ["12", "13", "14", "15", "16"],
    answer: "15",
    explanation: "A standard 3×3 magic square (using 1–9) always has a total of 15.",
    style: "magic-square", source: "kangaroo", points: 3,
  },
  {
    id: "cpz_y5_01", skill: "puzzles", year: 5, difficulty: 2, type: "mcq",
    text: "🔺 + 🔺 + ⬛ = 20. ⬛ + 🔺 = 13. What does 🔺 + ⬛ + ⬛ equal?",
    options: ["17", "18", "19", "20", "21"],
    answer: "19",
    explanation: "🔺 = 20 − 13 = 7. ⬛ = 13 − 7 = 6. 🔺 + ⬛ + ⬛ = 7 + 6 + 6 = 19.",
    style: "simultaneous-equations", source: "ukmt", points: 4,
  },
  {
    id: "cpz_y5_02", skill: "puzzles", year: 5, difficulty: 3, type: "mcq",
    text: "🦊 × 🐰 = 24. 🦊 + 🐰 = 10. 🦊 > 🐰. What is 🦊 − 🐰?",
    options: ["1", "2", "3", "4", "5"],
    answer: "2",
    explanation: "Numbers that multiply to 24 and add to 10: 6 and 4. 🦊=6, 🐰=4. Difference = 2.",
    style: "simultaneous-equations", source: "ukmt", points: 5,
  },
  {
    id: "cpz_y6_01", skill: "puzzles", year: 6, difficulty: 3, type: "mcq",
    text: "⭐ + ⭐ + 🎯 = 30. ⭐ + 🎯 + 🎯 = 27. What is ⭐ + 🎯?",
    options: ["17", "18", "19", "20", "21"],
    answer: "19",
    explanation: "Adding both equations: 3⭐ + 3🎯 = 57 → ⭐ + 🎯 = 19.",
    style: "simultaneous-equations", source: "ukmt", points: 5,
  },
  {
    id: "cpz_y3_02", skill: "puzzles", year: 3, difficulty: 1, type: "mcq",
    text: "🐘 + 🐭 = 15. 🐘 − 🐭 = 7. What is 🐘?",
    options: ["9", "10", "11", "12", "13"],
    answer: "11",
    explanation: "Adding equations: 2🐘 = 22 → 🐘 = 11.",
    style: "simultaneous-equations", source: "original", points: 3,
  },
  {
    id: "cpz_y6_02", skill: "puzzles", year: 6, difficulty: 3, type: "mcq",
    text: "In a 4×4 magic square, the magic total is 34. One row contains the values: 16, 3, 🔷, 13. What is 🔷?",
    options: ["1", "2", "3", "4", "5"],
    answer: "2",
    explanation: "16 + 3 + 🔷 + 13 = 34. 32 + 🔷 = 34. 🔷 = 2.",
    style: "magic-square", source: "original", points: 4,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// MEASUREMENT & DATA
// ─────────────────────────────────────────────────────────────────────────────
export const compMeasurementQuestions: Question[] = [
  {
    id: "cme_y4_01", skill: "measurement", year: 4, difficulty: 1, type: "mcq",
    text: "Five children's heights are 120cm, 115cm, 130cm, 125cm, 110cm. What is the mean height?",
    options: ["118cm", "120cm", "122cm", "124cm", "126cm"],
    answer: "120cm",
    explanation: "Sum = 600cm. Mean = 600 ÷ 5 = 120cm.",
    style: "mean-average", source: "pmc", points: 3,
  },
  {
    id: "cme_y5_01", skill: "measurement", year: 5, difficulty: 2, type: "mcq",
    text: "The mean of four numbers is 12. Three of them are 8, 15, and 11. What is the fourth?",
    options: ["12", "13", "14", "15", "16"],
    answer: "14",
    explanation: "Total = 4 × 12 = 48. Fourth = 48 − 8 − 15 − 11 = 14.",
    style: "mean-average", source: "ukmt", points: 4,
  },
  {
    id: "cme_y5_02", skill: "measurement", year: 5, difficulty: 2, type: "mcq",
    text: "Find the median of: 7, 3, 12, 5, 9, 1, 8.",
    options: ["5", "6", "7", "8", "9"],
    answer: "7",
    explanation: "Ordered: 1, 3, 5, 7, 8, 9, 12. The middle value (4th) = 7.",
    style: "median-real-data", source: "original", points: 3,
  },
  {
    id: "cme_y6_01", skill: "measurement", year: 6, difficulty: 3, type: "mcq",
    text: "Six test scores have mean 70. A seventh score of 84 is added. What is the new mean?",
    options: ["72", "73", "74", "75", "76"],
    answer: "72",
    explanation: "Original total = 420. New total = 504. New mean = 504 ÷ 7 = 72.",
    style: "mean-average", source: "ukmt", points: 4,
  },
  {
    id: "cme_y3_01", skill: "measurement", year: 3, difficulty: 1, type: "mcq",
    text: "A bottle holds 1.5 litres. How many 250ml cups can be filled from it?",
    options: ["4", "5", "6", "7", "8"],
    answer: "6",
    explanation: "1.5L = 1500ml. 1500 ÷ 250 = 6.",
    style: "standard", source: "pmc", points: 3,
  },
  {
    id: "cme_y4_02", skill: "measurement", year: 4, difficulty: 1, type: "mcq",
    text: "A spool has 5m of ribbon. Pieces of 35cm are cut from it. How many complete pieces can be cut?",
    options: ["12", "13", "14", "15", "16"],
    answer: "14",
    explanation: "5m = 500cm. 500 ÷ 35 = 14.28... So 14 complete pieces.",
    style: "standard", source: "pmc", points: 3,
  },
  {
    id: "cme_y5_03", skill: "measurement", year: 5, difficulty: 2, type: "mcq",
    text: "A rectangular field is 120m × 80m. A farmer walks around the perimeter 3 times. How far does she walk in kilometres?",
    options: ["1.0km", "1.1km", "1.2km", "1.4km", "1.6km"],
    answer: "1.2km",
    explanation: "Perimeter = 2(120+80) = 400m. Three laps = 1200m = 1.2km.",
    style: "compound-perimeter", source: "original", points: 3,
  },
  {
    id: "cme_y4_03", skill: "measurement", year: 4, difficulty: 1, type: "mcq",
    text: "A pie chart shows: 25% red, 35% blue, 20% green, rest yellow. In a group of 40 people, how many chose yellow?",
    options: ["6", "7", "8", "9", "10"],
    answer: "8",
    explanation: "Yellow = 100% − 80% = 20%. 20% of 40 = 8.",
    style: "pie-chart", source: "pmc", points: 3,
  },
  {
    id: "cme_y5_04", skill: "measurement", year: 5, difficulty: 2, type: "mcq",
    text: "On a pie chart, the sector for Cats has angle 90°. 600 people were surveyed. How many chose cats?",
    options: ["100", "125", "150", "175", "200"],
    answer: "150",
    explanation: "90° / 360° = 1/4. 1/4 × 600 = 150.",
    style: "pie-chart", source: "ukmt", points: 4,
  },
  {
    id: "cme_y5_05", skill: "measurement", year: 5, difficulty: 2, type: "mcq",
    text: "A car travels at 60km/h. How far does it travel in 45 minutes?",
    options: ["35km", "40km", "45km", "50km", "55km"],
    answer: "45km",
    explanation: "45 min = 3/4 hour. 60 × 3/4 = 45km.",
    style: "speed-distance-time", source: "pmc", points: 4,
  },
  {
    id: "cme_y6_02", skill: "measurement", year: 6, difficulty: 3, type: "mcq",
    text: "A cyclist rides 48km at 16km/h, then 30km at 10km/h. What is her average speed for the whole journey?",
    options: ["12km/h", "13km/h", "14km/h", "15km/h", "16km/h"],
    answer: "13km/h",
    explanation: "Time1 = 3h. Time2 = 3h. Total = 78km in 6h. Average = 13km/h.",
    style: "speed-distance-time", source: "ukmt", points: 5,
  },
  {
    id: "cme_y4_04", skill: "measurement", year: 4, difficulty: 2, type: "mcq",
    text: "A bag of rice weighs 2.5kg. How many grams is that?",
    options: ["250g", "500g", "1000g", "2500g", "25000g"],
    answer: "2500g",
    explanation: "1kg = 1000g. 2.5kg = 2500g.",
    style: "standard", source: "original", points: 3,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// TIME & CALENDAR
// ─────────────────────────────────────────────────────────────────────────────
export const compTimeQuestions: Question[] = [
  {
    id: "ct_y1_01", skill: "time", year: 1, difficulty: 1, type: "mcq",
    text: "School starts at 9 o'clock. Lunchtime is 3 hours later. What time is lunchtime?",
    options: ["11 o'clock", "12 o'clock", "1 o'clock", "2 o'clock", "3 o'clock"],
    answer: "12 o'clock",
    explanation: "9 + 3 = 12 o'clock (noon).",
    style: "time-arithmetic", source: "original", points: 3,
  },
  {
    id: "ct_y2_01", skill: "time", year: 2, difficulty: 1, type: "mcq",
    text: "A TV show starts at 6:15pm and lasts 45 minutes. What time does it finish?",
    options: ["6:45pm", "6:55pm", "7:00pm", "7:05pm", "7:15pm"],
    answer: "7:00pm",
    explanation: "6:15 + 45 minutes = 7:00pm.",
    style: "time-arithmetic", source: "pmc", points: 3,
  },
  {
    id: "ct_y3_01", skill: "time", year: 3, difficulty: 1, type: "mcq",
    text: "A film lasts 1 hour 50 minutes and starts at 3:30pm. What time does it end?",
    options: ["5:10pm", "5:15pm", "5:20pm", "5:25pm", "5:30pm"],
    answer: "5:20pm",
    explanation: "3:30 + 1h 50min = 5:20pm.",
    style: "time-arithmetic", source: "pmc", points: 3,
  },
  {
    id: "ct_y3_02", skill: "time", year: 3, difficulty: 2, type: "mcq",
    text: "How many minutes are there from 10:45am to 1:20pm?",
    options: ["145min", "150min", "155min", "160min", "165min"],
    answer: "155min",
    explanation: "10:45→11:00 = 15min. 11:00→1:00pm = 120min. 1:00→1:20 = 20min. Total = 155min.",
    style: "time-arithmetic", source: "original", points: 3,
  },
  {
    id: "ct_y4_01", skill: "time", year: 4, difficulty: 2, type: "mcq",
    text: "A train departs at 08:47 and arrives at 11:23. How long is the journey?",
    options: ["2h 26min", "2h 30min", "2h 36min", "2h 40min", "2h 46min"],
    answer: "2h 36min",
    explanation: "08:47→09:00 = 13min. 09:00→11:00 = 120min. 11:00→11:23 = 23min. Total = 156min = 2h 36min.",
    style: "time-arithmetic", source: "ukmt", points: 3,
  },
  {
    id: "ct_y4_02", skill: "time", year: 4, difficulty: 2, type: "mcq",
    text: "How many seconds are in one week?",
    options: ["50,400", "86,400", "302,400", "604,800", "1,209,600"],
    answer: "604,800",
    explanation: "60 × 60 × 24 × 7 = 604,800 seconds.",
    style: "time-arithmetic", source: "kangaroo", points: 4,
  },
  {
    id: "ct_y3_03", skill: "time", year: 3, difficulty: 1, type: "mcq",
    text: "Niamh's watch shows 7:20 but it is 10 minutes fast. What is the actual time?",
    options: ["7:10", "7:20", "7:25", "7:30", "7:40"],
    answer: "7:10",
    explanation: "If the watch is fast by 10 minutes, the real time is 10 minutes earlier: 7:10.",
    style: "time-arithmetic", source: "pmc", points: 3,
  },
  {
    id: "ct_y4_03", skill: "time", year: 4, difficulty: 1, type: "mcq",
    text: "A bus leaves every 20 minutes. The first bus is at 8:00am. What time is the 5th bus?",
    options: ["8:40am", "8:50am", "9:00am", "9:10am", "9:20am"],
    answer: "9:20am",
    explanation: "4 intervals of 20 min after 8:00am = 80 min later = 9:20am.",
    style: "time-arithmetic", source: "original", points: 3,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// EXPORT
// ─────────────────────────────────────────────────────────────────────────────
export const COMPETITION_QUESTIONS: Question[] = [
  ...compAdditionQuestions,
  ...compMultiplicationQuestions,
  ...compFractionQuestions,
  ...compShapesQuestions,
  ...compPatternsQuestions,
  ...compLogicQuestions,
  ...compPuzzleQuestions,
  ...compMeasurementQuestions,
  ...compTimeQuestions,
];

export default COMPETITION_QUESTIONS;
